### ISSUE TITLE
Can't upload to sm.ms "Could not create SSL/TLS secure channel."

### ISSUE THREAD

**Issue by pessoalzy** [ShareX/CustomUploaders#259]
I'm using ShareX 13.0.1 in Windows 10 1909.

I import the [sm.ms.sxcu](https://github.com/ShareX/CustomUploaders/blob/master/sm.ms.sxcu) and test it in the "Custom uploader setting". The test failed. Here is the Test Result:

```
Error message:
The request was aborted: Could not create SSL/TLS secure channel.

Request URL:
https://sm.ms/api/upload

Stack trace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by crsncc** [comment]
Try removing the s from the https
